### ISSUE TITLE
Cool GitHub feature "Contact Links"

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/.github#12]
I saw an interesting feature on another repository that allows for displaying custom links on the issue creation page by creating a  `ISSUE_TEMPLATE/config.yaml` file like so:

```yml
blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
```

A single `contact_link` renders like this:

<img width="1536" alt="Screen Shot 2020-06-29 at 9 42 51 AM" src="https://user-images.githubusercontent.com/6351754/86013335-09248f00-b9ed-11ea-9067-3a042d69e9b1.png">

Could be a nice way to direct users to wikis, community resources, or any other more specific channels for their issues.
